### ISSUE TITLE
ioa_stftCompute函数没有找到

### ISSUE THREAD

**Issue by longRookie** [LWZ9755/doa_traditional_algorithm#6]
老师您好，sound-source-localization-algorithm_DOA_estimation/ssl_tools/doa_mvdr.m 文件中第33行的ioa_stftCompute函数
![image](https://user-images.githubusercontent.com/68834517/158056649-e36bf68c-0f97-4e93-bfbb-15513543bc67.png)
我没有找到，请问我该如何解决？
可以使用spectrogram函数替换吗？

**Comment by WenzheLiu-Speech** [comment]
可以，也可以用doa_srp.m中的ssl_stft函数

**Comment by longRookie** [comment]
感谢您的解答

**Comment by letnnn** [comment]
你好，你最终怎么改的？

**Comment by letnnn** [comment]
> 老师您好，sound-source-localization-algorithm_DOA_estimation/ssl_tools/doa_mvdr.m 文件中第33行的ioa_stftCompute函数 ![image](https://user-images.githubusercontent.com/68834517/158056649-e36bf68c-0f97-4e93-bfbb-15513543bc67.png) 我没有找到，请问我该如何解决？ 可以使用spectrogram函数替换吗？

你最终如何解决的？
